### ISSUE TITLE
Fisherman is now Fisher

### ISSUE THREAD

**Issue by jorgebucaran** [fabianoleittes/dotfiles#1]
Hello @fabianoleittes. ~~Fisherman~~ is now [Fisher](https://github.com/jorgebucaran/fisher/). 

Could you replace all "Fisherman" or "fisherman" with "Fisher"? Can you update your tags too?

- ~~[`fishshell`](https://github.com/topics/fishshell)~~ → [`fish-shell`](https://github.com/topics/fish-shell) (or add)
- ~~`fisherman`~~ → [`fisher`](https://github.com/topics/fisher)

**Comment by fabianoleittes** [comment]
Hi @jorgebucaran Thank you for letting me know.
I'm going to replace everything.

**Comment by jorgebucaran** [comment]
@fabianoleittes Ping! :)

**Comment by jorgebucaran** [comment]
Missed a tag (GitHub topic): 
<img width="521" alt="screen shot 2019-01-31 at 1 55 19" src="https://user-images.githubusercontent.com/56996/51998058-484e6800-24fb-11e9-83c7-b1ad85d930be.png">

👋😉
